# Generated by Django 3.0.2 on 2020-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('adminname', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='profile.jpg', upload_to='images/')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('bio', models.TextField(max_length=500)),
                ('image', models.ImageField(default='profile.jpg', upload_to='')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.RunSQL("INSERT into Users(username,email,password,image) VALUES('admin','admin@gmail.com','admin','avatar.jpg'"),
        migrations.RunSQL("INSERT into admin(adminname,password) VALUES('admin','admin'")
    ]
